baseURL = 'https://ml4its.github.io/about'
languageCode = 'en-us'
title = 'ML4ITS - Machine Learning for Irregular Time Series'
theme = 'mainroad'
publishDir = "docs"


[Params.widgets.social]
  cached = false # activate cache if true
  # Enable parts of social widget
  github = "ml4its"
  email = "massimiliano.ruocco@sintef.no"

[Params]
  description = "ML4ITS website" 
  copyright = "Massimiliano Ruocco" 
  #post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  post_meta = ["categories", "translations"]

[Params.logo]
  image = "images/logoml4its.png" # Logo image. Path relative to "static"
  title = "ML4ITS" # Logo title, otherwise will use site title
  subtitle = "Machine Learning for Irregular Time Series" # Logo subtitle


[Params.thumbnail]
  #visibility = ["list", "post"] # Control thumbnail visibility
  visibility = ["list"] # Control thumbnail visibility

[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/home'
    weight = 1
[[menu.main]]
    name = 'Publications'
    pageRef = '/publications'
    weight = 2
[[menu.main]]
	name = 'Thesis'
	pageRef = '/thesis'
	weight = 3
[[menu.main]]
    name = 'Team'
    pageRef = '/team'
    weight = 4